name: Build and Release APK

on:
  push:
    tags:
      - 'v*' # 仅在推送匹配 v* 的标签时触发
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 检出代码
    - name: Checkout code
      uses: actions/checkout@v3

    # 设置 JDK 环境
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # 缓存 Gradle 构建文件以加速
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    # 构建 APK
    - name: Build APK
      run: ./gradlew assembleRelease

    # 上传 APK 到 GitHub Release
    - name: Upload APK to Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: app/build/outputs/apk/release/app-release.apk # 替换为你的APK路径
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |
          自动生成的 Release 版本。
